CREATE TABLE [dbo].[Tags]
(
	[TagId] INT NOT NULL PRIMARY KEY IDENTITY (1,1), 
    [TagName] VARCHAR(MAX) NOT NULL, 
    [BookId] INT NOT NULL CONSTRAINT fk_BookId FOREIGN KEY REFERENCES Books(BookId) ON UPDATE CASCADE ON DELETE CASCADE
)